name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # NEW: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GAR
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-ats-repo/myflaskapp:$GITHUB_SHA .
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-ats-repo/myflaskapp:$GITHUB_SHA

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy flask-ats-demo \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-ats-repo/myflaskapp:$GITHUB_SHA \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
