name: Build and Deploy to GCP Cloud Run

on:
  push:
    branches:
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Build and push Docker image to Artifact Registry
        run: |
          docker build -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-ats-repo/myflaskapp:$GITHUB_SHA .
          docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-ats-repo/myflaskapp:$GITHUB_SHA

      - name: Deploy to Cloud Run (public)
        run: |
          gcloud run deploy flask-ats-demo \
            --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-ats-repo/myflaskapp:$GITHUB_SHA \
            --platform managed \
            --region asia-south1 \
            --allow-unauthenticated
